version: "3.1"

services:
  notebook:
    build: .
    command: start-notebook.sh --NotebookApp.token=''
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan/work
